[project]
name = "thesis"
version = "0.1.0"
description = "Prefix tuning applicability in language models"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "transformers>=4.57.1",
    "datasets>=4.3.0",
    "ipython>=9.6.0",
    "marimo>=0.17.7",
    "polars>=1.34.0",
    "torch>=2.9.0",
    "peft>=0.17.1",
    "typer>=0.20.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.2",
    "ty>=0.0.1a25",
]
